name: Django CI

env:
  SPI_TOOLS_CONFIG_FILE: $GITHUB_WORKSPACE/unsafe-sample-config.ini

on:
  workflow_dispatch:

  push:
    branches: [ master dev-basedir ]
  pull_request:
    branches: [ master dev-basedir ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
